package com.my.project.fromwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-12-11T17:38:24.313+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://www.example.org/calc", name = "calcService")
public interface CalcService {

    @WebMethod(action = "http://www.example.org/calc/add")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/calc", className = "com.my.project.fromwsdl.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/calc", className = "com.my.project.fromwsdl.client.AddResponse")
    @WebResult(name = "addResult", targetNamespace = "http://www.example.org/calc")
    public int add(
        @WebParam(name = "num1", targetNamespace = "http://www.example.org/calc")
        int num1,
        @WebParam(name = "num2", targetNamespace = "http://www.example.org/calc")
        int num2
    );
}
