package com.my.project.fromjava.wsdl2java;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-12-11T18:44:50.488+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://fromjava.project.my.com/", name = "IMyService")
@XmlSeeAlso({ObjectFactory.class})
public interface IMyService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://fromjava.project.my.com/", className = "com.my.project.fromjava.wsdl2java.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://fromjava.project.my.com/", className = "com.my.project.fromjava.wsdl2java.SayHelloResponse")
    @WebResult(name = "helloMsg", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
