
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.my.project.fromjava.wsdl2java;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-12-11T18:44:50.466+08:00
 * Generated source version: 3.1.14
 * 
 */

@javax.jws.WebService(
                      serviceName = "MyServiceService",
                      portName = "MyServicePort",
                      targetNamespace = "http://fromjava.project.my.com/",
                      wsdlLocation = "http://localhost:9000/myService?wsdl",
                      endpointInterface = "com.my.project.fromjava.wsdl2java.IMyService")
                      
public class MyServicePortImpl implements IMyService {

    private static final Logger LOG = Logger.getLogger(MyServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.my.project.fromjava.wsdl2java.IMyService#sayHello(java.lang.String name)*
     */
    public java.lang.String sayHello(java.lang.String name) { 
        LOG.info("Executing operation sayHello");
        System.out.println(name);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
