
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.my.project.spring.wsdl2java;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-12-11T18:49:16.743+08:00
 * Generated source version: 3.1.14
 * 
 */

@javax.jws.WebService(
                      serviceName = "calcService",
                      portName = "calcServicePort",
                      targetNamespace = "http://www.example.org/calc",
                      wsdlLocation = "http://localhost:8080/hello-cxf/services/calcService?wsdl",
                      endpointInterface = "com.my.project.spring.wsdl2java.CalcService")
                      
public class CalcServicePortImpl implements CalcService {

    private static final Logger LOG = Logger.getLogger(CalcServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.my.project.spring.wsdl2java.CalcService#add(int num1, int num2)*
     */
    public int add(int num1, int num2) { 
        LOG.info("Executing operation add");
        System.out.println(num1);
        System.out.println(num2);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
