
package com.my.project.fromwsdl.wsdl2java;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-12-11T18:45:31.170+08:00
 * Generated source version: 3.1.14
 * 
 */
public final class CalcService_CalcServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/calc", "calcService");

    private CalcService_CalcServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalcService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalcService_Service ss = new CalcService_Service(wsdlURL, SERVICE_NAME);
        CalcService port = ss.getCalcServicePort();  
        
        {
        System.out.println("Invoking add...");
        int _add_num1 = 0;
        int _add_num2 = 0;
        int _add__return = port.add(_add_num1, _add_num2);
        System.out.println("add.result=" + _add__return);


        }

        System.exit(0);
    }

}
